### ISSUE TITLE
Download form doesn't work

### ISSUE THREAD

**Issue by kuzmany** [mautic/website#74] opened 2019-03-27 08:15 UTC
http://staging.mautic.org/download

- No error statement
- Now download

**Comment by RCheesley** [comment] 2019-03-28 21:04
Just reviewing this and I can't replicate it - if I complete the form the download initiates without any problems. Did you fix it already @kuzmany ?

**Comment by RCheesley** [comment] 2019-03-28 21:06
Ohhh, maybe the issue is that the Mautic form is not showing an error if you do not complete the form?

**Comment by kuzmany** [comment] 2019-03-28 21:07
Yes, exactly.

**Comment by RCheesley** [comment] 2019-03-28 21:11
Gotcha, I'm not sure if that's something on our styling end, or the Mautic instance end? Any ideas? Ideally the field should go red, however my understanding was that you aren't supposed to require an email address to provide a download any more, perhaps @dbhurley could clarify Mautic's stance on this?

**Comment by kuzmany** [comment] 2019-04-05 07:18
Maybe CORS setting, maybe just require refresh form cache.

**Comment by RCheesley** [comment] 2019-04-05 10:22
I don't think it is, because CORS usually highlights in the browser console. This is just failing silently. I don't have access to the Mautic instance to review the form settings or refresh the cache, probably something that @dbhurley needs to do :(

**Comment by RCheesley** [comment] 2019-04-16 19:03
@dbhurley assigning this to you as I don't have access to check what's going on with this form!

**Comment by RCheesley** [comment] 2019-08-29 12:14
No longer relevant

**Closed as completed by RCheesley** 2019-08-29 12:14 UTC
Labels: Bug, P1
